name: Run example notebooks

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    # TODO: Find a way to run on all PRs before merge, but not blindly on all commits 
    name: Run example notebooks on Test on ${{ matrix.cfg.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.6
          - 3.7
        cfg:
          - os: ubuntu-latest
          - os: macOS-latest

    env:
      CI_OS: ${{ matrix.cfg.os }}
      PYVER: ${{ matrix.python-version }}
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt
      PACKAGE: openforcefield

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        name: Install toolkit and example dependencies
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: test
          environment-file: devtools/conda-envs/examples.yaml
          auto-activate-base: false

      - name: Additional info about the build
        shell: bash -l {0}
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Make oe_license.txt file from GH org secret "OE_LICENSE"
        shell: bash
        env:
          OE_LICENSE_TEXT: ${{ secrets.OE_LICENSE }}
        run: |
          echo "${OE_LICENSE_TEXT}" > ${OE_LICENSE}

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -v .

      - name: Run example notebooks
        shell: bash -l {0}
        continue-on-error: true
        run: |
          PYTEST_ARGS="pytest -v --nbval-lax --ignore=examples/deprecated"
          pytest $PYTEST_ARGS examples/
